version: '3'
services:
  library-service:
    image: library-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - library-database
  library-database:
    image: postgres