DROP TABLE IF EXISTS books;
CREATE TABLE books(id BIGINT generated by default as identity, name VARCHAR(255));

DROP TABLE IF EXISTS book_history;
CREATE TABLE book_history(id BIGINT generated by default as identity, old_name VARCHAR(255), book_id BIGINT,
                      FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

